language: php
php:
- 7.2
- 7.3
- 7.4
before_install:
- travis_retry composer self-update
install:
- travis_retry composer install --no-interaction --prefer-dist
script:
- composer run test
- composer run lint
- composer run analyze
env:
  global:
  - SQUARE_ENVIRONMENT=sandbox
  - secure: XgT4Pd6y+ktSKzd6rLjnYAh6ZJgOn9Gzqyt0NV4BTpbJdYcfkDX2TbLHRlwjiMg9j5/vBdBfHEWo5EH82/tx/vFHKsAtVi7fivyv4k1d5Ik9gU5IxLj8sExnc6KLej8joB2IlHDyV7TaWdNWjSjQLSmnPJ0Ikc+1IKmQI4KLCCbESagSAheT0AYWMZ7pCm794VRkRW+k3F6y7EVbgyCw/WzjFTh6yr88YIzAgs8KDTswZdrEj5Hc6K3FvZQKKyXetOpAHRXzS5YSscx5dimXZad7xYvc/R5rfJIMxPlKyjiYHI2bC8MJNmvpjYiQhuYPSA/RRFEqEc6aOHdiOLUevZlZIqsMGuoiUbBX1e6Ip0Qy5jBbMBDuHFSX19AUeCL9WSQSqTCa/0o1I/kDo98vsApbUN2AnOr4BvQCw+hvlBsgnUMFMsH15UMfQXjbmjWovI8lKRhpc7Un2m1QGD2JZesWYXJlPsd2UOLYsAi/itOH8oP7c8blQGhzEXh+joEzV1KvEfKt4/WQ9VSJyCVAbS3+NORrBR3GBAVwYyvdaJIDdmZB6lGrAoGE4opHqy34oxyC7ulWeGcXPDOekT01u+3xOjmZTSFcCWO7KJr9m2BH+AskE4JotTwOnJmEvztQzOJ9L/mt2M4DE7BlC9K3pmTyeQbVvQfGxp465596lLE=
  - secure: oYrdRvSugvE2/x9mmECRXZ6xLhnIwijMBD66d4vYPPvAd9NrAyQWiQ+bsWw3bwp1K5DXC0JsAhyHI+587ZoYaHUTL0guejjHKkBk89eOLqyDa55oPNTlgSlrfVKSjMpS9bfwQPDmvdjWGcGyPVR7ZYNX+dqKjlusT7AYyvfr+guOgjcfyob4sA5pTfjwo/1vQZSNxw7jVn7d3xZUf6REJNIJ0MVu2Exi3KhsJRlcGQaXgg3g4Fo1+G4B7qAN6sxdHnOtFtb+vlBAHSJsStbmss873DXzjJnYWkFLshhoqvrIpYQNhkQ+3YkpZuDAJgFLK+l8flDs+nITz6G05YShEVH57EzTaVrxRMNt4SrUWZLJ6kc1YrixPNrYgOyYSLZ5cd8TzFmnFIELNkZm2tTr0uoJERZx0KZ/Nnu+Ew5QX8ruOZrCinUUb9xkN1yTn+UGkbtksqGUvxSsYdq47vfyBSpJp3Mgq0e+8MBqx2jf2T0aui+mTnNlU9mCC5qgeuVL1VTxlmqxJkdEA2bD2ac1aqGC/5m8kcW8e0OFRauQbMmGGR4RgdKf+BXJuj9ZI7WKiFnPLvTtprQBkcld14ZGXH8qgiZIXY5urPAVhwe9Bs37rlRMQ5Ht5a7R2bS739xKsX3UocRh39yzOpvVbA9UubsrwDu/kjGEnAD+wToS/fY=
